version: '3.8'
services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    depends_on:
      - kafka
  kafka:
    extends:
      file: kafka/docker-compose.yml
      service: kafka
  zookeeper:
    extends:
      file: kafka/docker-compose.yml
      service: zookeeper
